{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:06.758Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:13.282Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:19.900Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:26.488Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:33.069Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:39.722Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:46.375Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:53.037Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:52:59.706Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:09.774Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:16.491Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:23.134Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:29.775Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:36.503Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:43.126Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:49.727Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:53:56.363Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:03.003Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:12.520Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:19.089Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:25.677Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:32.299Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:38.884Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:45.482Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:52.072Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:54:58.692Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:55:05.292Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:55:13.672Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["Error: getaddrinfo ENOTFOUND quote-postgres\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)"],"timestamp":"2025-03-19T14:55:20.276Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:25.597Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:28.615Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:31.634Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:34.650Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:37.708Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:40.731Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:43.746Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:46.831Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:49.849Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:53.718Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:56.747Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:55:59.789Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:02.807Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:05.822Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:08.848Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:11.867Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:14.892Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:17.918Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:19.894Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:22.917Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:25.948Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:28.965Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:31.985Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:35.005Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:38.016Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:41.041Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:44.062Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:46.281Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:49.303Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:52.322Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:55.353Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:56:58.372Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:01.386Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:04.409Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:07.427Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:10.447Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:12.689Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:15.717Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:18.736Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:21.764Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:24.790Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:27.821Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:30.844Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:33.869Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:36.890Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:39.081Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:42.100Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:45.117Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:48.134Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:51.157Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:54.185Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:57:57.206Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:00.237Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:03.259Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:05.260Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:08.281Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:11.301Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:14.318Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:17.345Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:20.367Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:23.389Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:26.417Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:29.441Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:31.458Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:34.482Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:37.505Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:40.520Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:43.541Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:46.566Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:49.582Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:52.596Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:55.614Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:58:57.752Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:00.779Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:03.796Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:06.811Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:09.831Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:12.848Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:15.862Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:18.880Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:21.898Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:24.059Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:27.080Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:30.114Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:44.200Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:47.224Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:50.249Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:53.263Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:56.292Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T14:59:59.310Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:02.323Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:05.339Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:08.362Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:10.530Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:13.555Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:16.577Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:19.604Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:22.623Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:25.638Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:28.670Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:31.686Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:34.705Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:36.918Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:39.936Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:42.955Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:45.984Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:49.004Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:52.038Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:55.059Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:00:58.071Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:01.091Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:03.272Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:06.290Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:09.312Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:12.327Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:15.339Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:18.362Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:21.382Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:24.400Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:27.437Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:29.479Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (2)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:32.526Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (3)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:35.560Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (4)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:38.587Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (5)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:41.607Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (6)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:44.640Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (7)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:47.657Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (8)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:50.681Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (9)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:53.714Z"}
{"context":"TypeOrmModule","level":"error","message":"Unable to connect to the database. Retrying (1)...","stack":["error: database \"quote\" does not exist\n    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"],"timestamp":"2025-03-19T15:01:55.734Z"}
